# Generated by Django 4.0.4 on 2022-06-13 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscriber',
            field=models.ManyToManyField(through='accounts.Subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
